acornaccounting/core/urls.py
from django.conf.urls import patterns, url

from .forms import BootstrapAuthenticationForm


urlpatterns = patterns(
    '',

    url(r'^$', 'accounts.views.show_accounts_chart', name='homepage'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html',
         'authentication_form': BootstrapAuthenticationForm},
        name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'},
        name='logout'),
)

acornaccounting/fiscalyears/urls.py
from django.conf.urls import patterns

urlpatterns = patterns(
    'fiscalyears.views',

    (r'^$', 'add_fiscal_year'),
)

acornaccounting/fiscalyears/models.py
import calendar
import datetime

from caching.base import CachingManager, CachingMixin
from django.db import models


class FiscalYear(CachingMixin, models.Model):
    """
    A model for storing data about the Company's Past and Present Fiscal Years.

    The Current Fiscal Year is used for generating Account balance's and
    Archiving :class:`~accounts.models.Account` instances into
    :class:`HistoricalAccounts<accounts.models.HistoricalAccount>`.

    .. seealso::

        View :func:`~.views.add_fiscal_year`
            This view processes all actions required for starting a New Fiscal
            Year.

    .. attribute:: year

        The ending Year of the Financial Year.

    .. attribute:: end_month

        The ending Month of the Financial Year. Stored as integers, displayed
        with full names.

    .. attribute:: period

        The length of the Fiscal Year in months. Available choices are 12 or
        13.

    .. attribute:: date

        The first day of the last month of the Fiscal Year. This is not
        editable, it is generated by the :class:`FiscalYear` when saved, using
        the :attr:`end_month` and :attr:`year` values.

    """
    PERIOD_CHOICES = (
        (12, '12 Months'),
        (13, '13 Months')
    )
    MONTH_CHOICES = tuple((num, mon) for num, mon in
                          enumerate(calendar.month_name[1:], 1))
    year = models.PositiveIntegerField()
    end_month = models.PositiveSmallIntegerField(choices=MONTH_CHOICES)
    period = models.PositiveIntegerField(choices=PERIOD_CHOICES)
    # TODO: Turn either year/month or the date into a function, maybe
    # seemlessly by making them properties.
    date = models.DateField(editable=False, blank=True)

    objects = CachingManager()

    class Meta:
        ordering = ('date',)
        get_latest_by = ('date',)

    def __unicode__(self):
        return "Fiscal Year {0}-{1}".format(self.year, self.end_month)

    def save(self, *args, **kwargs):
        """
        The :class:`FiscalYear` ``save`` method will generate the
        :class:`~datetime.date` object for the :attr:`date` attribute.
        """
        self.full_clean()
        self.date = datetime.date(self.year, self.end_month, 1)
        super(FiscalYear, self).save(*args, **kwargs)

acornaccounting/fiscalyears/views.py
import calendar
import datetime

from dateutil import rrule
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render

from accounts.models import Account, HistoricalAccount
from entries.models import (Transaction, JournalEntry, BankSpendingEntry,
                            BankReceivingEntry)
from events.models import Event, HistoricalEvent


from .fiscalyears import get_start_of_current_fiscal_year
from .forms import FiscalYearForm, FiscalYearAccountsFormSet
from .models import FiscalYear


@login_required
def add_fiscal_year(request, template_name="fiscalyears/year_add.html"):
    """
    Creates a new :class:`~.models.FiscalYear` using a
    :class:`~.forms.FiscalYearForm` and
    :data:`~.forms.FiscalYearAccountsFormSet`.

    Starting a new :class:`~.models.FiscalYear` involves the following
    procedure:

         1. Setting a ``period`` and Ending ``month`` and ``year`` for the New
            Fiscal Year.
         2. Selecting Accounts to exclude from purging of unreconciled
            :class:`Transactions<entries.models.Transaction>`.
         3. Create a :class:`~accounts.models.HistoricalAccount` for every
            :class:`~accounts.models.Account` and month in the previous
            :class:`~.models.FiscalYear`, using ending balances for Asset,
            Liability and Equity :class:`Accounts<accounts.models.Account>` and
            balance changes for the others.
         4. Delete all :class:`Journal Entries<entries.models.JournalEntry>`,
            except those with unreconciled
            :class:`Transactions<entries.models.Transaction>` with
            :class:`Accounts<accounts.models.Account>` in the exclude lists.
         5. Move the ``balance`` of the ``Current Year Earnings``
            :class:`~accounts.models.Account` into the ``Retained Earnings``
            :class:`~accounts.models.Account`.
         6. Zero the ``balance`` of all Income, Cost of Sales, Expense, Other
            Income and Other Expense
            :class:`Accounts<accounts.models.Account>`.

    :param template_name: The template to use.
    :type template_name: string
    :returns: HTTP response containing
            :class:`~.forms.FiscalYearForm` and
            :data:`~.forms.FiscalYearAccountsFormSet` as context.
            Redirects if successful POST is sent.
    :rtype: HttpResponse or HttpResponseRedirect

    """
    previous_year = _get_previous_year_if_exists()

    if request.method == 'POST':
        fiscal_year_form = FiscalYearForm(request.POST)
        accounts_formset = FiscalYearAccountsFormSet(request.POST)
        valid = fiscal_year_form.is_valid() and accounts_formset.is_valid()
        if valid and previous_year:
            start_of_previous_year = get_start_of_current_fiscal_year()
            end_of_previous_year = _get_last_day_of_month(previous_year.date)

            [_archive_and_delete_event(event) for event in
             Event.objects.filter(date__lte=end_of_previous_year)]

            months_in_previous_year = _get_months_in_range(
                start_of_previous_year, end_of_previous_year)
            for month in months_in_previous_year:
                last_day_of_month = _get_last_day_of_month(month)
                HistoricalAccount.objects.bulk_create(
                    [_build_historical_account(account, last_day_of_month) for
                     account in Account.objects.all()]
                )

            excluded_transactions = _get_excluded_transactions(
                accounts_formset)

            journals = [Journal.objects.filter(date__lte=end_of_previous_year)
                        for Journal in (JournalEntry, BankReceivingEntry,
                                        BankSpendingEntry)]
            for entries in journals:
                for entry in entries:
                    _delete_entry_if_not_excluded(entry, excluded_transactions)
            [_correct_account_balance(account, end_of_previous_year) for
             account in Account.objects.all()]

            _transfer_current_year_earnings(end_of_previous_year)

            fiscal_year_form.save()
            messages.success(request, "Your previous fiscal year has been "
                             "closed and a new fiscal year has been started.")
            return HttpResponseRedirect(reverse(
                'accounts.views.show_accounts_chart'))
        elif valid:
            fiscal_year_form.save()
            messages.success(request, "A new fiscal year has been started.")
            return HttpResponseRedirect(reverse(
                'accounts.views.show_accounts_chart'))
    else:
        fiscal_year_form = FiscalYearForm()
        accounts_formset = FiscalYearAccountsFormSet(
            queryset=Account.objects.order_by('last_reconciled',
                                              'full_number'))
    return render(request, template_name, locals())


def _get_previous_year_if_exists():
    """Return the last FiscalYear or False if none exists."""
    try:
        previous_year = FiscalYear.objects.latest()
    except FiscalYear.DoesNotExist:
        previous_year = False
    return previous_year


def _archive_and_delete_event(event):
    """Create a HistoricalEvent and delete the Event."""
    debit_total, credit_total, net_change = event.transaction_set.get_totals(
        net_change=True)

    HistoricalEvent.objects.create(
        name=event.name, number=event.number, date=event.date, city=event.city,
        state=event.state, debit_total=debit_total, credit_total=credit_total,
        net_change=net_change)
    event.delete()


def _get_months_in_range(start_date, stop_date):
    """Return a list of datetime.date months between the start & stop dates."""
    return rrule.rrule(rrule.MONTHLY, dtstart=start_date, until=stop_date)


def _build_historical_account(account, month):
    """Create a HistoricalAccount for the specified account and month."""
    if account.type in (1, 2, 3):
        amount = account.get_balance_by_date(date=month)
    else:
        amount = account.get_balance_change_by_month(month)

    if account.flip_balance():      # Flip back to credit/debit
        amount *= -1                # amount from value amount

    historical_account = HistoricalAccount(
        account=account, date=month, name=account.name, type=account.type,
        number=account.get_full_number(), amount=amount)
    return historical_account


def _get_excluded_transactions(accounts_formset):
    """
    Process a FiscalYearAccountsFormSet and return a set of excluded
    Transactions.

    """
    excluded_accounts = [form.instance for form in accounts_formset if
                         form.cleaned_data.get('exclude')]
    excluded_transactions = frozenset(Transaction.objects.filter(
        account__in=excluded_accounts, reconciled=False))
    return excluded_transactions


def _get_last_day_of_month(month):
    """Return the last day of the specified month."""
    last_day_of_month = month.replace(
        day=calendar.monthrange(month.year, month.month)[1])
    return last_day_of_month


def _get_all_transactions(entry):
    """Get all Transactions of the Entry, including a main_transaction."""
    entry_transactions = list(entry.transaction_set.all())
    if hasattr(entry, 'main_transaction'):
        entry_transactions.append(entry.main_transaction)
    return entry_transactions


def _delete_entry_if_not_excluded(entry, excluded_transactions):
    """Delete an Entry if none of it's Transactions are excluded."""
    entry_transactions = _get_all_transactions(entry)
    entry_is_not_excluded = excluded_transactions.isdisjoint(
        entry_transactions)
    if entry_is_not_excluded:
        [transaction.delete() for transaction in entry_transactions]
        entry.delete()


def _correct_account_balance(account, historical_year_end):
    """
    Set the Account balance to the latest HistoricalAccount balance plus any
    Transactions after the end of the last Fiscal Year.

    """
    new_year_sum = account.transaction_set.filter(
        date__gt=historical_year_end).aggregate(Sum('balance_delta'))
    account.balance = new_year_sum.get('balance_delta__sum') or 0
    if account.type in (1, 2, 3):
        hist_acct = account.historicalaccount_set.latest()
        account.balance += hist_acct.amount
    account.save()


def _transfer_current_year_earnings(entry_date):
    """Transfer the Current Year Earnings balance into Retained Earnings."""
    current_earnings = Account.objects.get(name='Current Year Earnings')
    retained_earnings = Account.objects.get(name='Retained Earnings')
    historical_current = current_earnings.historicalaccount_set.latest()
    transfer_date = entry_date + datetime.timedelta(days=1)

    entry = JournalEntry.objects.create(date=transfer_date,
                                        memo='End of Fiscal Year Adjustment')
    Transaction.objects.create(journal_entry=entry, account=current_earnings,
                               balance_delta=historical_current.amount * -1)
    Transaction.objects.create(journal_entry=entry, account=retained_earnings,
                               balance_delta=historical_current.amount)

acornaccounting/fiscalyears/templates/fiscalyears/year_add.html
{% extends 'site.html' %}

{% load staticfiles %}

{% block title %}New Fiscal Year{% endblock title %}


{% block page_header %}
  <h1>Start a New Fiscal Year</h1>
{% endblock %}

{% block content %}

<div class="alert alert-danger">
    <p><span class="glyphicon glyphicon-warning-sign"></span><strong> Danger!</strong> Starting a new Fiscal Year will cause mass
    deletion of Journal Entries and Transactions. Please backup your data before proceeding.</p>

    <p>After starting a new Year, you will not be able to edit or create Journal
    Entries in the current Year.</p>
</div>

<p>Starting a new Fiscal Year involves:</p>
  <ol>
    <li>Creating Account Histories for every month in the current Fiscal
    Year.</li>
    <li>Deleting all Journal Entries in the current Year that do not have
    unreconciled Transactions for Accounts in the Exclude list.</li>
    <li>Zeroing the balance of all Income, Cost of Sales, Expense, Other
    Income and Other Expense Accounts.</li>
    <li>Moving the current Year's balance of the Current Year Earnings
    Equity Account into the Retained Earnings Equity Account.</li>
  </ol>

<p>If this is your first Fiscal Year, no Journal Entries will be purged and no
Historical Accounts will be created. The warnings and benefits only apply to
subsequent Fiscal Years.</p>

<p>You can start a short Fiscal Year by changing the ending month of the new
Year.</p>

<p>It is always possible to switch from a 12 month period to a 13 month period.
However, if switching from a 13 month period to a 12 month period, there
must be no Transactions in the 13th month of the current Year.</p>

<!-- Error Alert -->
{% if fiscal_year_form.non_field_errors %}
  <br />
  <div class="alert alert-danger">
      <span class="glyphicon glyphicon-minus-sign"></span><strong> Error!</strong> Please correct the following issues before continuing:
    <ul>
      {% for error in fiscal_year_form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  </div>
{% endif %}

<form data-validate="parsley" action="." method="POST" id="fiscal-year-form"
    name="fiscal_year_form" role="form">
  {% csrf_token %}
  <table class="table table-condensed">
    {% if previous_year %}
      <thead>
        <tr>
          <th></th>
          <th>Current Year</th>
          <th>New Year</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th><label for="id_year">Year:</label></th>
          <td>{{ previous_year.year }}</td>
          <td><div class="controls">{{ fiscal_year_form.year }}{{ fiscal_year_form.year.errors }}</div></td>
        </tr>
        <tr>
          <th><label for="id_end_month">End month:</label></th>
          <td>{{ previous_year.get_end_month_display }}</td>
          <td class="form-group{% if fiscal_year_form.end_month.errors %} has-error{% endif %}">{{ fiscal_year_form.end_month }}{{ fiscal_year_form.end_month.errors }}</td>
        </tr>
        <tr>
          <th><label for="id_period">Period:</label></th>
          <td>{{ previous_year.get_period_display }}</td>
          <td class="form-group{% if fiscal_year_form.period.errors %} has-error{% endif %}">{{ fiscal_year_form.period }}{{ fiscal_year_form.period.errors }}</td>
        </tr>
      </tbody>
    {% else %}
      <div class="form-horizontal">
        {% for field in fiscal_year_form %}
          <div class ="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.id_for_label }}" class="control-label col-sm-2">{{ field.label }}:</label>
            <div class="col-sm-3 controls">
              {{ field }}
            </div>
            {% if field.errors %}
              {% for error in field.errors %}
                <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="help-block"><strong>{{ error }}</strong></p>
              {% endfor %}
            {% endif %}
          </div>
        {% endfor %}
      </div>
    {% endif %}
  </table>
  <br />
  <p>
  Select the Accounts you reconcile regularly to prevent deletion of their
  unreconciled Transactions. Accounts that have been previously reconciled are
  selected by default.
  </p>
  <br />
  {{ accounts_formset.management_form }}
  <div id="fiscal-year-accounts">
    <table class="table table-condensed table-hover">
      <thead>
        <tr>
          <th>Exclude</th>
          <th>Account</th>
          <th>Last Reconciled</th>
        </tr>
      </thead>
      <tbody>
        {% for form in accounts_formset %}
          <tr class="{% cycle 'main' 'alt' %}">
            {% for hidden in form.hidden_fields %}
              {{ hidden }}
            {% endfor %}
            <td>{{ form.visible_fields.0 }}</td>
            <td>{{ form.instance.name }}</td>
            <td>{{ form.instance.last_reconciled|date:"m/d/y"|default_if_none:"" }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <br \><br \>
  <button type="submit" id="submit-button" name="submit" value="Start New Year" data-target="#confirmModal" class="btn btn-danger">Start New Year&hellip;</button>

<!-- Confirmation Modal -->
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="confirmModalLabel">Confirm Fiscal Year Creation and Transaction Purging</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to start a new Fiscal Year? Closing the
        current Year will delete all its Journal Entries and prevent creation
        of new Entries.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" id="confirm-button" class="btn btn-danger">Start New Year</button>
      </div>
    </div>
  </div>
</div>

</form>
<br \>
{% endblock content %}


{% block javascript %}
<script type="text/javascript" src="{% static 'js/parsley.js' %}"></script>
<script type="text/javascript">
    $(document).ready( function() {
        /* Close Modal if invalid form */
        $( '#submit-button' ).click( function(el) {
            el.preventDefault();

            if ($( '#fiscal-year-form' ).parsley( 'isValid' )) {
                $( '#confirmModal' ).modal( 'show' );
            } else {
                $( '#fiscal-year-form' ).parsley( 'validate' )
            }
        });
    });
</script>
{% endblock %}