acornaccounting/accounts/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'accounts.views',

    (r'^$', 'show_accounts_chart'),

    url(r'^detail/(?P<account_slug>[-\w]+)/$', 'show_account_detail',
        name='show_account_detail'),
    (r'^(?P<account_slug>[-\w]+)/reconcile/$', 'reconcile_account'),

    (r'^header/(?P<header_slug>[-\w]+)/$', 'show_accounts_chart'),

    (r'^history/$', 'show_account_history'),
    (r'^history/(?P<year>\d{2}(?:\d{2})?)/(?P<month>\d(?:\d)?)/',
     'show_account_history'),

    (r'^search/account/$', 'quick_account_search'),
    (r'^search/bank-journal/$', 'quick_bank_search'),

    url(r'^bank-journal/(?P<account_slug>[-\w]+)/$', 'bank_journal',
        name='bank_journal'),

    url(r'^ajax/accounts/$', 'accounts_query', name='accounts_query'),
)

acornaccounting/core/urls.py
from django.conf.urls import patterns, url

from .forms import BootstrapAuthenticationForm


urlpatterns = patterns(
    '',

    url(r'^$', 'accounts.views.show_accounts_chart', name='homepage'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html',
         'authentication_form': BootstrapAuthenticationForm},
        name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'},
        name='logout'),
)

acornaccounting/accounts/forms.py
from django import forms
from django.forms.formsets import (INITIAL_FORM_COUNT, TOTAL_FORM_COUNT)
from django.forms.models import (modelformset_factory,
                                 BaseModelFormSet)
from django.forms.util import ErrorList
from parsley.decorators import parsleyfy

from entries.models import Transaction

from .models import Account


class QuickAccountForm(forms.Form):
    account = forms.ModelChoiceField(
        queryset=Account.objects.none(), label='', empty_label='',
        widget=forms.Select(
            attrs={'onchange': 'this.form.submit();',
                   'class': 'form-control account-autocomplete',
                   'placeholder': 'Jump to an Account'}),
    )


class QuickBankForm(forms.Form):
    bank = forms.ModelChoiceField(
        queryset=Account.objects.active().order_by('name').filter(bank=True),
        widget=forms.Select(attrs={'onchange': 'this.form.submit();',
                                   'class': 'form-control autocomplete-select',
                                   'placeholder': 'Jump to a Bank Journal'}),
        label='', empty_label=''
    )


@parsleyfy
class AccountReconcileForm(forms.ModelForm):
    statement_date = forms.DateField(widget=forms.DateInput(
        attrs={'data-americandate': True,
               'class': 'form-control'}))
    statement_balance = forms.DecimalField(widget=forms.TextInput(
        attrs={'class': 'form-control'}))

    class Meta:
        model = Account
        fields = ('statement_date', 'statement_balance')

    def clean_statement_balance(self):
        """Convert from a value balance to a credit/debit balance."""
        balance = self.cleaned_data.get('statement_balance')
        if self.instance.flip_balance():
            balance *= -1
        return balance

    def clean_statement_date(self):
        """Ensure the Statement Date is after the Last Reconciled Date."""
        statement_date = self.cleaned_data.get('statement_date')
        if (self.instance.last_reconciled is not None and
                statement_date < self.instance.last_reconciled):
            raise forms.ValidationError("The Statement Date must be later "
                                        "than the Last Reconciled Date.")
        return statement_date


class BaseReconcileTransactionFormSet(BaseModelFormSet):
    class Meta:
        model = Transaction
        widgets = {
            'reconciled': forms.CheckboxInput(attrs={'class': 'form-control'})
        }

    def clean(self):
        """Checks that Reconciled amounts balance with the Statement amount."""
        self._check_for_deleted_transactions()
        super(BaseReconcileTransactionFormSet, self).clean()
        if any(self.errors):
            return self.cleaned_data if hasattr(self, 'cleaned_data') else None
        balance = (self.account_form.cleaned_data.get('statement_balance') -
                   self.reconciled_balance)
        for form in self.forms:
            if form.cleaned_data.get('reconciled'):
                balance -= form.instance.balance_delta
        if balance != 0:
            raise forms.ValidationError("The selected Transactions are out of "
                                        "balance with the Statement Amount.")

    def _check_for_deleted_transactions(self):
        """Validate that No Deleted Transactions are Checked.

        Also removes any unchecked but deleted Transactions from the forms.

        """
        deleted_transaction_selected = False
        removed_forms = 0
        for (index, form) in enumerate(self.forms):
            form_id = self.data[form.prefix + '-id']
            if not Transaction.objects.filter(id=form_id).exists():
                if form.data[form.prefix + "-reconciled"] != "False":
                    deleted_transaction_selected = True
                del self.forms[index]
                removed_forms += 1

        total_form_key = self.management_form.prefix + "-TOTAL_FORMS"
        self.management_form.data[total_form_key] = int(self.management_form.data[total_form_key]) - removed_forms

        for (index, error) in enumerate(self.errors):
            if 'id' in error:
                if any("valid choice" in id_error for id_error in error['id']):
                    del self.errors[index]

        if deleted_transaction_selected:
            raise forms.ValidationError(
                "You selected a deleted Transaction for reconciliation.")

    def add_form(self, instance):
        """Add a new form instance to a bound Formset."""
        if self.is_bound:
            self.forms.append(self._construct_form(
                self.total_form_count(), instance=instance))
            self.management_form.cleaned_data[INITIAL_FORM_COUNT] += 1
            self.management_form.cleaned_data[TOTAL_FORM_COUNT] += 1


ReconcileTransactionFormSet = modelformset_factory(
    Transaction, extra=0, can_delete=False, fields=('reconciled',),
    formset=BaseReconcileTransactionFormSet)

acornaccounting/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from parsley.decorators import parsleyfy


class RequiredFormSetMixin(object):
    """This class ensures at least one form in the formset is filled."""
    def clean(self):
        """Ensure that at least one filled form exists."""
        super(RequiredFormSetMixin, self).clean()
        count = 0
        for form in self.forms:
            if (hasattr(form, 'cleaned_data') and not
                    form.cleaned_data.get('DELETE', True)):
                count += 1
                break

        if count < 1:
            raise forms.ValidationError("At least one Transaction is required "
                                        "to create an Entry.")


class RequiredBaseFormSet(RequiredFormSetMixin, forms.models.BaseFormSet):
    """A BaseFormSet that requires at least one filled form."""


class RequiredBaseInlineFormSet(RequiredFormSetMixin,
                                forms.models.BaseInlineFormSet):
    """A BaseInlineFormSet that requires at least one filled form."""


@parsleyfy
class DateRangeForm(forms.Form):
    """A form for acquiring a DateRange via a start_date and enddate."""
    start_date = forms.DateField(label="Start Date",
                                 widget=forms.DateInput(
                                     attrs={'data-americandate': True,
                                            'size': 8,
                                            'class': 'form-control'})
                                 )
    stop_date = forms.DateField(label="Stop Date",
                                widget=forms.DateInput(
                                    attrs={'data-americandate': True,
                                           'size': 8,
                                           'class': 'form-control'})
                                )


class BootstrapAuthenticationForm(AuthenticationForm):
    """A login form using bootstrap attributes."""
    def __init__(self, *args, **kwargs):
        """Add the form-control CSS class to all fields"""
        super(BootstrapAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'

acornaccounting/accounts/templates/accounts/account_charts.html
{% extends "site.html" %}

{% load core_filters %}


{% block title %}
Chart of Accounts{% if header %} - {{ header.name|capwords }}{% endif %}
{% endblock %}


{% block page_header %}
  <h1>Chart of Accounts <small class="hidden-print">{% if header %}{{ header.name|capwords }}{% endif %}</small></h1>
  {% if header %}
    <h4 class="visible-print">{{ header.name|capwords }}</h4>
  {% endif %}

  <!-- Breadcrumbs -->
  {% if header %}
    <ol class="breadcrumb hidden-print">
      <li><a href="{% url accounts.views.show_accounts_chart %}">Chart of Accounts</a></li>
      {% for ancestor in header.get_ancestors %}
        <li><a href="{{ ancestor.get_absolute_url }}">{{ ancestor.name|capwords }}</a></li>
      {% endfor %}
      <li class="active">{{ header.name|capwords }}</li>
    </ol>
  {% endif %}
{% endblock %}


{% block content %}

{% if not header %}
  <!-- Tabs -->
  <ul class="nav nav-tabs hidden-print">
    {% for root_node in root_nodes %}
      <li {% if forloop.first %}class="active"{% endif %}><a href="#{{ root_node.slug }}" data-toggle="tab">{{ root_node.name|capwords }}</a></li>
    {% endfor %}
  </ul>
{% endif %}


<!-- Panes -->
<div class="tab-content">
  {% for root_node in root_nodes %}
    <div class="tab-pane fade {% if forloop.first %}active in{% endif %}" id="{{ root_node.slug }}">
      <table summary="Chart of Accounts" id="accounts_chart" class="table table-hover table-condensed">
        <thead>
        <tr>
          <th scope="col">Number</th>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col" class="text-right">Balance</th>
        </tr>
        </thead>
          <tbody>
          {% for node in root_node.descendants %}
            <tr class="header clickable">
              <td><a href="{{ node.get_absolute_url }}">{{ node.get_full_number }}</a></td>
              <td><a href="{{ node.get_absolute_url }}">{{ node.level|int_to_tabs}}{{ node.name|capwords }}</a></td>
              <td><a href="{{ node.get_absolute_url }}">{{ node.description }}</a></td>
              <td class="text-right"><a href="{{ node.get_absolute_url }}">{{ node.get_account_balance|currency }}</a></td>
            </tr>
            {% for account in node.account_set.all|dictsort:"full_number" %}
              <tr class="{% cycle 'main' 'alt' %} clickable">
                <td><a href="{{ account.get_absolute_url }}">{{ account.get_full_number }}</a></td>
                <td><a href="{{ account.get_absolute_url }}">{{ account.level|int_to_tabs}}{{ account.name|capwords }}</a></td>
                <td><a href="{{ account.get_absolute_url }}">{{ account.description }}</a></td>
                <td class="text-right"><a href="{{ account.get_absolute_url }}">{{ account.get_balance|currency}}</a></td>
              </tr>
            {% endfor %}
          {% endfor %}
          </tbody>
      </table>
  </div>
  {% endfor %}
</div>

{% endblock %}

acornaccounting/accounts/templates/accounts/account_detail.html
{% extends "site.html" %}

{% load core_filters %}
{% load core_tags %}
{% load staticfiles %}


{% block title %}{{ account.name|capwords }} Details{% endblock %}


{% block page_header %}
  <h3 class="visible-print"></h3>
  <h1><span class="hidden-print">#{{ account.get_full_number }} </span>{{ account.name|capwords }} <small>{{ account.get_balance|currency }}</small></h1>
  <h4 class="visible-print">Account #{{ account.get_full_number }}<br />
    {{ start_date }} to {{ stop_date }}</h4>

<!-- Breadcrumbs -->
  <ol class="breadcrumb hidden-print">
    <li><a href="{% url accounts.views.show_accounts_chart %}">Chart of Accounts</a></li>
    {% for ancestor in account.parent.get_ancestors %}
      <li><a href="{{ ancestor.get_absolute_url }}">{{ ancestor.name|capwords }}</a></li>
    {% endfor %}
    <li><a href="{{ account.parent.get_absolute_url }}">{{ account.parent.name|capwords }}</a></li>
    <li class="active">{{ account.name|capwords }}</li>
  </ol>
{% endblock %}


{% block post_header %}
  <!-- Buttons -->
  <div class="hidden-print">
    {% if account.bank %}<a href="{% url accounts.views.bank_journal account.slug %}" class="btn btn-default btn-sm" role="button"><span class="glyphicon glyphicon-list"></span> Bank Journal</a>{% endif %}
    <a href="{% url accounts.views.reconcile_account account_slug=account.slug %}" class="btn btn-default btn-sm" role="button"><span class="glyphicon glyphicon-book"></span> Reconcile</a>
    <a href="{% url admin:accounts_account_change account.id %}" class="btn btn-default btn-sm" role="button"><span class="glyphicon glyphicon-edit"></span> Edit</a>
  </div>
  <br />
{% endblock %}


{% block content %}

<div class="hidden-print">
  <!-- Account Information -->
  {% if account.last_reconciled %}
    <p><strong>Last Reconciled:</strong> {{ account.last_reconciled|date:"m/d/Y" }}</p>
  {% endif %}

  <!-- Date Range Form -->
  {% date_range_form form %}
</div>


<table summary="{{ account.name }} Details" id="accounts_chart" class="table table-hover table-condensed">
  <thead>
    <tr>
        <th scope="col">Number</th>
        <th scope="col">Date</th>
        <th scope="col">Memo</th>
        <th scope="col">Detail</th>
        <th scope="col" class="text-right">Debit</th>
        <th scope="col" class="text-right">Credit</th>
        <th scope="col" class="text-right">Event</th>
        {% if show_balance %}
            <th scope="col" class="text-right">Balance</th>
        {% endif %}
    </tr>
  </thead>
  <!-- Transactions Table -->
  <tbody>
    {% for transaction in transactions %}
      <tr class="{% cycle 'main' 'alt' %} clickable">
      <td><a href="{{ transaction.get_journal_entry.get_absolute_url }}">{{ transaction.get_entry_number }}</a></td>
      <td><a href="{{ transaction.get_journal_entry.get_absolute_url }}">{{ transaction.date|date:"m/d/Y" }}</a></td>
      <td><a href="{{ transaction.get_journal_entry.get_absolute_url }}">{{ transaction.get_memo|capwords }}</a></td>
      <td><a href="{{ transaction.get_journal_entry.get_absolute_url }}">{{ transaction.detail|capwords }}</a></td>
      {% if transaction.balance_delta < 0 %}
        <td class="text-right"><a href="{{ transaction.get_journal_entry.get_absolute_url }}">{{ transaction.balance_delta|currency }}</a></td>
        <td class="text-right"></td>
      {% else %}
        <td class="text-right"></td>
        <td class="text-right"><a href="{{ transaction.get_journal_entry.get_absolute_url }}">{{ transaction.balance_delta|currency }}</a></td>
      {% endif %}
      <td class="text-right">
        {% if transaction.event %}
        <a href="{{ transaction.event.get_absolute_url }}">{{ transaction.event }}</a>
        {% endif %}
      </td>
      {% if show_balance %}
        <td class="text-right"><a href="{{ transaction.get_journal_entry.get_absolute_url }}">{{ transaction.final_balance|currency }}</a></td>
      {% endif %}
      </tr>
    {% endfor %}
  </tbody>
  <!-- Balance and Change Counter -->
  <tfoot>
    <tr><td colspan="{% if show_balance %}8{% else %}7{% endif %}">&nbsp;</td></tr>
    <tr>
      {% if show_balance %}
        <td class="text-right" colspan="2"><strong>Start Balance:</strong></td>
        <td>{{ start_balance|currency }}</td>
      {% else %}
          <td colspan="3"></td>
      {% endif %}
      <td class="text-right"><strong>Totals:</strong></td>
      <td class="text-right">{{ debit_total|currency }}</td>
      <td class="text-right">{{ credit_total|currency }}</td>
      <td colspan="2"></td>
    </tr>
    <tr>
      {% if show_balance %}
        <td class="text-right" colspan="2"><strong>End Balance:</strong></td>
          <td>{{ end_balance|currency }}</td>
      {% else %}
          <td colspan="3"></td>
      {% endif %}
        <td class="text-right"><strong>Net Change:</strong></td>
        {% if net_change < 0 %}
          <td class="text-right">{{ net_change|currency }}</td>
          <td class="text-right"></td>
        {% else %}
          {% if net_change > 0 %}
            <td class="text-right"></td>
            <td class="text-right">{{ net_change|currency }}</td>
          {% else %}
            <td class="text-right">$0.00</td>
            <td class="text-right">$0.00</td>
          {% endif %}
        {% endif %}
        <td></td>
        {% if show_balance %}
          <td></td>
        {% endif %}
    </tr>
  </tfoot>
</table>
<br /><br />

{% endblock %}


{% block javascript %}
<script type="text/javascript" src="{% static 'js/parsley.js' %}"></script>
<script type="text/javascript" src="{% static 'js/parsley.extend.js' %}"></script>
<script type="text/javascript">
    $(document).ready( function () {
        /* Automatically Select the Start Date Field */
        $("input#id_start_date").focus();
        /* Validate the date range form w/ parsley */
        $('#date_range_form').parsley({
            successClass: 'has-success',
            errorClass: 'has-error',
            errors: {
                classHandler: function (el) {
                    return $(el).closest('.form-group');
                },
                errorsWrapper: '<ul></ul>',
                errorElem: '<li></li>'
            }
        });
    });
</script>
{% endblock %}

acornaccounting/accounts/templates/accounts/account_reconcile.html
{% extends 'site.html' %}

{% load core_filters %}
{% load staticfiles %}


{% block title %}Reconcile {{ account }}{% endblock %}


{% block page_header %}
  <h1>Reconcile {{ account }}</h1>
{% endblock %}


{% block content %}

{% if transaction_formset %}
  <!-- Info Alert -->
  <div class="alert alert-info">
    <p><span class="glyphicon glyphicon-info-sign"></span> If you edit any
    Entries after visiting this page and you wish to update this page, do not
    refresh the page, but instead submit an invalid form. This will allow you
    to retain the form's data while updating the Entries.</p>
  </div>
{% endif %}


<!-- Statement Form -->
<form action="." method="POST" id="reconcile_form">
{% csrf_token %}

<div class="form-horizontal">
  {% for field in account_form %}
    <div class ="form-group{% if field.errors %} has-error{% endif %}">
      <label for="{{ field.id_for_label }}" class="control-label col-sm-2">{{ field.label }}:</label>
      <div class="col-sm-3 controls">
        {{ field }}
      </div>
      {% if field.errors %}
        {% for error in field.errors %}
          <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="help-block"><strong>{{ error }}</strong></p>
        {% endfor %}
      {% endif %}
    </div>
  {% endfor %}
  <div class ="form-group">
    <label for="last-reconciled" class="control-label col-sm-2">Last Reconciled:</label>
    <div class="col-sm-3">
      <p id="last-reconciled" class="form-control-static">{{ last_reconciled|date:"m/d/Y"|default:"Never" }}</p>
    </div>
  </div>
  <div class ="form-group">
    <label for="reconciled-balance" class="control-label col-sm-2">Reconciled Balance:</label>
    <div class="col-sm-3">
      <p id="reconciled-balance" class="form-control-static">{{ reconciled_balance|currency }}</p>
    </div>
  </div>
  <div class ="form-group">
    <div class="col-sm-2 col-sm-offset-2">
      <button type="submit" name="submit" value="Get Transactions" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-list"></span> Get Transactions</button>
    </div>
  </div>
</div>

<!-- Transaction Formset -->
{% if transaction_formset %}
  {{ transaction_formset.management_form }}

  <!-- Error Alert -->
  {% if transaction_formset.errors %}
    <br />
    <div class="alert alert-danger">
      <span class="glyphicon glyphicon-minus-sign"></span><strong> Error!</strong> Please correct the following issues before continuing:
      <ul>
        {% for error in transaction_formset.non_form_errors %}
            <li>{{ error }}</li>
        {% endfor %}
        {% for form in transaction_formset %}
          {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
            {% endfor %}
            {% for field in form %}
              <li>{{ field.errors }}</li>
            {% endfor %}
          {% endif%}
        {% endfor %}
      </ul>
    </div>
  {% endif %}

  <table class="table table-condensed table-hover">
    <thead>
      <tr>
        <th><input type="checkbox" class="checkall"  name="checkall"/></th>
        <th>Date</th>
        <th>Number</th>
        <th>Memo</th>
        <th class="text-right">Debit</th>
        <th class="text-right">Credit</th>
        <th class="text-right">Event</th>
        <th class="text-right">Edit</th>
      </tr>
    </thead>
    <tbody>
      {% for form in transaction_formset %}
        <tr class="{% cycle 'main' 'alt' %} markable">
          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}
          <td>{{ form.visible_fields.0.errors.as_ul }}{{ form.visible_fields.0 }}</td>
          <td>{{ form.instance.date|date:"m/d/y" }}</td>
          <td>{{ form.instance.get_entry_number }}</td>
          <td>{{ form.instance.get_memo }}</td>
          {% if form.instance.balance_delta < 0 %}
            <td class="text-right debit">{{ form.instance.balance_delta|currency }}</td>
            <td class="text-right credit"></td>
          {% else %}
            <td class="text-right debit"></td>
            <td class="text-right credit">{{ form.instance.balance_delta|currency }}</td>
          {% endif %}
          <td class="text-right">{{ form.instance.event|default_if_none:"" }}</td>
          <td class="text-right"><a target="_blank" href="{{ form.instance.get_journal_entry.get_edit_url }}">Edit</a></td>
        </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr><td colspan="8">&nbsp;</td></tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td class="text-right"><strong>Total:</strong></td>
        <td id="debit_total" class="text-right"></td>
        <td id="credit_total" class="text-right"></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td class="text-right"><strong>Net Change:</strong></td>
        <td id="net_change" class="text-right">$0.00</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td class="text-right"><strong>Out of Balance:</strong></td>
        <td id="out_of_balance" class="text-right">$0.00</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </tfoot>
  </table>
  <div class="form-group">
    <button type="submit" name="submit" value="Reconcile Transactions" class="btn btn-primary btn-sm col-sm-offset-2"><span class="glyphicon glyphicon-book"></span> Reconcile Transactions</button>
  </div>
  {% endif %}
</form><br /><br />

{% endblock %}


{% block javascript %}
<script type="text/javascript" src="{% static 'js/parsley.js' %}"></script>
<script type="text/javascript" src="{% static 'js/parsley.extend.js' %}"></script>
<script type="text/javascript">
    $(document).ready( function () {
        $('#reconcile_form').parsley({
            successClass: 'has-success',
            errorClass: 'has-error',
            errors: {
                classHandler: function (el) {
                    return $(el).closest('.form-group');
                },
                errorsWrapper: '<ul></ul>',
                errorElem: '<li></li>'
            }
        });
    });
</script>

{% if transaction_formset %}
  <script type="text/javascript">
      $(document).ready(function() {
        /* Recalculate counters on checkbox and Statement Balance changes. */
        $('#reconcile_form input:checkbox').change(function() {recalcCounters()});
        $('#id_account-statement_balance').keyup(function() {recalcCounters()});
        recalcCounters();

        /* Toggle all rows when the checkbox in the Table Header is changed. */
        $('.checkall').change(function () {
          $(this).closest('table').find(':checkbox').prop('checked', this.checked);
          if (this.checked) {
            $(this).closest('table').find('.markable').addClass('danger');
          } else {
            $(this).closest('table').find('.markable').removeClass('danger');
          }
          recalcCounters();
        });

        /* Toggle the 'danger' class on a table body row when the row's
           checkbox is changed.
         */
        $('.markable').find(':checkbox').on("change", function() {
          $(this).closest('tr').toggleClass('danger');
        });

        /* Make entire table rows clickable, so you don't have to aim for the
         * checkbox.
         */
        $('.markable').on('click', function(e) {
          if (e.target.type !== 'checkbox') {
            $(this).find(':checkbox').click();
          }
        });
      });

      /* Recalculate the Credit, Debit & Net Change counters in the table footer. */
      var recalcCounters = function () {
          // Calculate and set the Credit Total
          var credit_sum = 0;
          $(".credit").each(function(){
              if($(this).closest('tr').find('input:checkbox').is(':checked') == true) {
                  var trimmed = $(this).html().replace('$', '').replace(',', '');
                  if(!isNaN(trimmed) && trimmed.length != 0) {
                      credit_sum += parseFloat(trimmed);
                  }
              }
          });
          if (isNaN(credit_sum)) {credit_sum = 0}
          $('#credit_total').text('$' + roundTwo(credit_sum));

          // Calculate and set the Debit Total
          var debit_sum = 0;
          $(".debit").each(function(){
              if( $(this).closest('tr').find('input:checkbox').is(':checked') == true) {
                  var trimmed = $(this).html().replace('($', '').replace(')', '').replace(',', '');
                  if(!isNaN(trimmed) && trimmed.length != 0) {
                      debit_sum += parseFloat(trimmed);
                  }
              }
          });
          $('#debit_total').text('($' + roundTwo(debit_sum) + ')');

          // Calculate and set the Net Change
          var net_change = roundTwo(credit_sum - debit_sum);
          $('#net_change').text(formatCurrency(net_change));

          var statement_balance = parseFloat($('#id_account-statement_balance').val());
          if (isNaN(statement_balance)) {
              statement_balance = 0;
          }
          statement_balance = convertToCreditBalance(statement_balance);

          var reconciled_balance = convertToCreditBalance({{ reconciled_balance }});

          // Calculate and Set the Out of Balance Amount
          var statement_change = statement_balance - reconciled_balance;
          var out_of_balance = roundTwo(statement_change - net_change);
          $('#out_of_balance').text(formatCurrency(out_of_balance));
      };

      // Convert a Value Balance to a Credit Balance for this Account.
      function convertToCreditBalance(value_balance) {
          if ( {{ account.flip_balance|lower }} ) {
              value_balance = -1 * parseFloat(value_balance);
          }
          return value_balance;
      };

      // Display Negative Numbers in Parenthesis.
      function formatCurrency(amount) {
          var result;
          if (amount < 0) {
              result = '($' + Math.abs(amount) + ')';
          } else if (amount > 0) {
              result = '$' + amount;
          } else {
              result = '$0.00';
          }
          return result
      };
  </script>
{% endif %}

{% endblock %}